# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Mob Programming Unconference EU"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Mob Programming Unconference EU"
  description = "First Mob Programming Unconference in Europe"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Mob Programming Unconference EU"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "What is it about?"
    portfolio = "Details"
    about = "Schedule"
    # team = "Team"
    contact = "Register"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://github.com/HackYourJob/MobProgrammingUnconfEU/wiki"
      name = "Wiki"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "June 18-19th 2020, Villefranche-sur-Saône, France"
    subtitle = "Mob Programming Unconference Europe"
    buttonText = "Tell me more"


  # Services section
  [params.services]
    enable = true
    title = "What is it ?"
    subtitle = "Unconference ? Mob Programming ? Let us give some explanations."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-shopping-cart"
      title = "Unconference"
      description = "It is a conference without predefined talks, speakers and agenda. It is following Open Space format, where all attendees will build the conference content. Organization only propose a venue welcoming you for 2 days & 3 nights."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Mob Programming"
      description = "There is no specific subjects, but we have a theme around Mob Programming. There will be probably coding sessions (in mob ?), discussions around practices and even unattended subjects if participants want to!"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-lock"
      title = "Open to everyone"
      description = "There are no requirements on technology you work with or context at your work, just some interest and curiosity to Mob Programming and exchanges with people. You can also come accompanied and spend some additional days in our region, see [details](#details). **Note: official language will be English**."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Details"
    subtitle = "All the details you need to know to come."

    [params.portfolio.modal]
      # client = "Client"
      # date = "Date"
      # category = "Category"
      buttonText = "Close"

    # About section
  [params.about]
    enable = true
    title = "Schedule"
    subtitle = "There is no agenda but a rough schedule."
    endpoint = "Hope to see you soon!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "2.jpg"
      date = "Wednesday June 17th 2020"
      title = "Arriving and welcome activities"
      description = "You can arrive when you want in the afternoon, ideally before dinner to meet people and then kick off the unconference in the evening."

    [[params.about.events]]
      img = "1.jpg"
      date = "Thursday June 18th 2020"
      title = "Sessions all day & evening activities"
      description = "Day start with a 'marketplace' where sessions are proposed, sessions are typically from 10AM to 5:30PM, quick closing and then place to evening activities (alone or together)."

    [[params.about.events]]
      img = "3.jpg"
      date = "Friday June 19th 2020"
      title = "Sessions all day & evening activities"
      description = "Another 'marketplace' to start, then same agenda than Thursday, closing unconference with other evening activities."

    [[params.about.events]]
      img = "4.jpg"
      date = "Saturday June 20th 2020"
      title = "Time to get back home or visit our region!"
      description = "You can quit on Friday evening but you would miss part of the unconference with evening activities. Stay around for the weekend if you want to discover the countryside or Lyon - city of gastronomy!"


  # Team section
  [params.team]
    enable = false
    # Possibility to center items
    #center = true
    title = "Our amazing team"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kay Garland"
      position = "Lead Designer"
      reportsTo = "CTO"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "UX for [member dashboard](#)",
        "Maintainer for [awesome-project](#)",
        "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
She worked at Pied Piper for years until they went belly up."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Larry Parker"
      position = "Lead Marketer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Diana Pertersen"
      position = "Lead Developer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      # [[params.clients]]
      #   logo = "envato.jpg"
      #   link = "#"

      # [[params.clients]]
      #   logo = "designmodo.jpg"
      #   link = "#"

      # [[params.clients]]
      #   logo = "themeforest.jpg"
      #   link = "#"

      # [[params.clients]]
      #   logo = "creative-market.jpg"
      #   link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Register"
    subtitle  = "So are you interested ? Click below and fill in the form and we will send you the invoice (to pay as soon as possible please, to confirm venue reservation)."
    description = """
This conference is organized by [HackYourJob Community](https://www.hackyourjob.org).

If you need anything, contact us on Twitter [@HackYrJob](https://twitter.com/HackYrJob) or by email [contact@hackyourjob.org](mailto:contact@hackyourjob.org)."""
    buttonText = "Register"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    # email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    # [params.contact.form.name]
    #   text = "Your Name *"
    #   warning = "Please enter your name."

    # [params.contact.form.email]
    #   text = "Your Email *"
    #   warning = "Please enter your email address."

    # [params.contact.form.phone]
    #   text = "Your Phone *"
    #   warning = "Please enter your phone number."

    # [params.contact.form.message]
    #   text = "Your Message *"
    #   warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/hackyrjob"
      title = "Twitter"

    # [[params.footer.social]]
    #   icon = "fa-facebook"
    #   link = "#"
    #   title = "Facebook"

    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   link = "#"
    #   title = "LinkedIn"

    # [[params.footer.quicklinks]]
    #   text = "Privacy Policy"
    #   link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "/terms-of-use/"
